"""Email-related schemas for classification and drafting."""

from datetime import datetime
from enum import Enum
from typing import Annotated

from pydantic import BaseModel, Field

from realtorai.schemas.common import ChainOfReasoning, Confidence, ContactReference


class EmailPriority(str, Enum):
    """Email priority levels."""

    CRITICAL = "critical"  # Time-sensitive, requires immediate attention
    HIGH = "high"  # Important, should handle today
    NORMAL = "normal"  # Standard priority
    LOW = "low"  # Can wait, informational


class EmailIntent(str, Enum):
    """Classified intent of an email."""

    QUESTION = "question"  # Asking for information
    REQUEST = "request"  # Requesting an action
    INFORMATION = "information"  # Providing information, FYI
    CONFIRMATION = "confirmation"  # Confirming something
    SCHEDULING = "scheduling"  # About scheduling/calendar
    DOCUMENT = "document"  # Document-related (sending, requesting)
    NEGOTIATION = "negotiation"  # Offer, counter-offer, terms
    INTRODUCTION = "introduction"  # New client/contact intro
    FOLLOWUP = "followup"  # Following up on previous conversation
    ADMINISTRATIVE = "administrative"  # Admin stuff, newsletters, etc.
    OTHER = "other"


class EmailClassification(BaseModel):
    """Structured classification of an incoming email.

    This is the output schema for the email triage agent.
    """

    # Sender identification
    sender: Annotated[ContactReference, Field(description="Email sender")]

    # Classification
    intent: Annotated[EmailIntent, Field(description="Primary intent of the email")]
    priority: Annotated[EmailPriority, Field(description="Priority level")]
    requires_response: Annotated[bool, Field(description="Whether a response is needed")]

    # Context
    subject_summary: Annotated[str, Field(max_length=200, description="Brief summary of subject")]
    key_points: Annotated[
        list[str], Field(max_length=5, description="Key points from the email")
    ]

    # Relationships
    related_transaction: Annotated[
        str | None, Field(default=None, description="Related transaction/deal if identifiable")
    ]
    mentioned_contacts: Annotated[
        list[ContactReference], Field(default_factory=list, description="Other contacts mentioned")
    ]

    # Deadline extraction
    deadline_mentioned: Annotated[
        datetime | None, Field(default=None, description="Any deadline mentioned")
    ]
    deadline_description: Annotated[
        str | None, Field(default=None, description="Description of deadline")
    ]

    # Model confidence
    confidence: Annotated[Confidence, Field(description="Classification confidence")]


class DraftResponse(BaseModel):
    """A draft email response generated by the model."""

    subject: Annotated[str, Field(description="Email subject line")]
    body: Annotated[str, Field(description="Email body text")]

    # Formatting hints
    is_reply: Annotated[bool, Field(default=True, description="Is this a reply or new email")]
    include_signature: Annotated[bool, Field(default=True, description="Include agent signature")]

    # Attachments to include
    suggested_attachments: Annotated[
        list[str], Field(default_factory=list, description="Suggested attachments by name/type")
    ]


class EmailProposal(BaseModel):
    """Complete proposal for handling an email, shown in approval queue.

    Combines classification, reasoning, and draft response.
    """

    # Original email reference
    email_id: Annotated[str, Field(description="Graph API email ID")]
    thread_id: Annotated[str | None, Field(default=None, description="Thread/conversation ID")]
    received_at: Annotated[datetime, Field(description="When email was received")]

    # Classification
    classification: Annotated[EmailClassification, Field(description="Email classification")]

    # Reasoning chain
    reasoning: Annotated[ChainOfReasoning, Field(description="How we decided what to do")]

    # Proposed action
    proposed_action: Annotated[str, Field(description="What we propose to do")]
    draft_response: Annotated[
        DraftResponse | None, Field(default=None, description="Draft response if applicable")
    ]

    # Context provided to model
    thread_summary: Annotated[
        str | None, Field(default=None, description="Summary of email thread")
    ]

    @property
    def display_summary(self) -> str:
        """Summary for display in approval queue."""
        sender = self.classification.sender.name or self.classification.sender.email
        return f"{sender}: {self.classification.subject_summary}"
