"""Render docs/field-utilization.md — field reuse across every fill target.

The mapping itself lives in `realtorai.evals.field_map`; this is only the
renderer. That split exists because `evals.schema_coverage` enforces the same
map, and when the logic lived here it ran at import time and wrote a file as a
side effect, so nothing could reuse it.

    python scripts/field_utilization.py            # regenerate the doc
    python scripts/field_utilization.py --check    # CI: fail if it drifted
"""

import argparse
import pathlib
import sys

from realtorai.evals.field_map import (
    DESTINATION_LABELS,
    destination_map,
    mls_required_fields,
)

DOC = pathlib.Path(__file__).resolve().parent.parent / "docs" / "field-utilization.md"


def render() -> str:
    usage = destination_map()
    required = mls_required_fields()

    rows = sorted(
        ((len(dests), field, dests, field in required) for field, dests in usage.items()),
        key=lambda r: (-r[0], r[1]),
    )

    lines = [
        "# Field utilization across the workflow's paperwork and online forms",
        "",
        "Every destination one captured fact flows into. Counts = separate",
        "manual entries the deterministic fill replaces.",
        "",
        "Generated by `scripts/field_utilization.py` from",
        "`realtorai.evals.field_map`. Do not edit by hand — CI checks it.",
        "",
        "| Key | Destination |",
        "|---|---|",
        *(f"| {tag} | {label} |" for tag, label in DESTINATION_LABELS.items()),
        "",
        "| Uses | Field | MLS-required | Destinations |",
        "|---:|---|:---:|---|",
    ]
    total = 0
    for count, field, dests, req in rows:
        total += count
        lines.append(f"| {count} | `{field}` | {'yes' if req else ''} | {', '.join(dests)} |")

    reused = sum(1 for count, _f, _d, req in rows if req and count > 1)
    lines += [
        "",
        f"**Canonical fields tracked: {len(rows)}** · "
        f"**total field-entries across destinations: {total}** · "
        f"**MLS-required fields reused beyond the MLS: {reused}/49**",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit 1 if the committed doc differs from what the code implies.",
    )
    args = parser.parse_args()

    content = render()
    if args.check:
        current = DOC.read_text() if DOC.exists() else ""
        if current != content:
            print(
                f"{DOC.relative_to(DOC.parents[1])} is stale — "
                "run `python scripts/field_utilization.py` and commit the result.",
                file=sys.stderr,
            )
            return 1
        print(f"{DOC.name} is current.")
        return 0

    DOC.write_text(content)
    n_fields = content.count("\n| ") - len(DESTINATION_LABELS)
    print(f"wrote {DOC} ({n_fields} field rows)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
